# Generated by Django 5.0 on 2023-12-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
    ]
